site_name: Auto Maximize Nodes 插件帮助文档
site_url: https://chenpaner.github.io/Auto-Maximize-Nodes-Help/
nav:
  - 首页: index.md
  - 安装指南: installation.md
  - 使用说明: usage.md
  - 常见问题: faq.md
  - 联系与支持: contact.md
theme:
  name: mkdocs
  language: zh
docs_dir: src_docs
site_dir: docs